using EASY_CALLENDER01.SERVICES.FILE_SERVICES.TEXT_FILES;
using MySql.Data.MySqlClient;  
using EASY_CALLENDER01.SERVICES.MYSQL_SERVICES.MYSQL_HELPER;

namespace EASY_CALLENDER01.SERVICES.MYSQL_SERVICES.MYSQL_MANAGER.MYSQl_NEWS_MANAGER
{
    internal class MySql_News_Manager01
    {
    }
}
