using EASY_CALLENDER01.SERVICES.FILE_SERVICES.TEXT_FILES;
using MySql.Data.MySqlClient;  
using EASY_CALLENDER01.SERVICES.MYSQL_SERVICES.MYSQL_HELPER;

namespace EASY_CALLENDER01.SERVICES.MSQL_SERVICES.MYSQL.MYSQL_MANAGER.MYSQL_NFL_MANAGER
{
    internal class MySql_Nfl_Manager01
    {
    }
}
